#include "Constants.h"

u64 GAME_STATE_STACK[MAX_DEPTH + MAX_TURNS][15];
int GAME_STATE_STACK_POINTER = -1;

int MOVE_STACK_POINTER = 0;
Move MOVE_STACK[MAX_DEPTH][MAX_MOVES];

int CANCEL_THREAD = 0;
